---
- name: install epel repository
  yum:
    name: epel-release
    state: present

- name: install yum packages
  yum:
    state: present
    name: 
    - device-mapper-persistent-data
    - lvm2
    - python-pip
  when: ansible_os_family == "RedHat"

- name: install yum docker repository
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: remove distribution docker package
  yum:
    name: 
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      # - docker-selinux
      # - docker-engine-selinux
      - docker-engine
    state: absent
  when: ansible_os_family == "RedHat"

- name: install latest stable docker
  yum:
    state: present
    name: 
    - docker-ce
  when: ansible_os_family == "RedHat"
